**Introduction to NumPy and its purpose in Python for numerical computation.
Why NumPy is faster than Python lists.**

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Importing NumPy
import numpy as np

In [3]:
[[[[12113,121,23,],[12,3243,4565]]]]

[[[[12113, 121, 23], [12, 3243, 4565]]]]

In [5]:
# Larger dataset
list_data_large = list(range(10000000))
array_data_large = np.array(list_data_large)

# Python list time
%timeit [x + 1 for x in list_data_large]

# NumPy array time
%timeit array_data_large + 1

542 ms ± 62.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
24.7 ms ± 2.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


**How to create arrays from lists, ranges, and using built-in functions like zeros(), ones(), eye(), and arange().**

In [6]:
# list1= [12,34,12,23]
# print(type(list1))
# arr1=np.array(list1)
# print(type(arr1))

arr1=np.array([[[1,2,3,3],[3,4,2,1]]])
# arr1

arr2 = np.arange(63,95,2)
# arr2

arr3 = np.ones((2,3,4))
# arr3

arr5 =np.eye(10)
arr5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
# Creating arrays
arr_from_list = np.array([1, 2, 3, 4])
print("Array from list:", arr_from_list)

arr_range = np.arange(1, 10, 2)
print("Array with a range of numbers:", arr_range)

# 2x3 matrix of zeros
arr_zeros = np.zeros((2,3))
print("2x3 matrix of zeros:\n", arr_zeros)

# Identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity matrix:\n", identity_matrix)

Array from list: [1 2 3 4]
Array with a range of numbers: [1 3 5 7 9]
2x3 matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
np.ones((5,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.eye(10)#10*10 ka matrix hai

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**Array Indexing and Slicing**

**Explain how to access elements in arrays and slice them for sub-arrays.**

In [10]:
ar1 = np.array([[[12,2,34,54,56,67],[12,23,34,45,78,89]],[[12,12,34,54,56,89],[10, 20, 30, 40, 50,90]]])
ar1[1,0,2:]

array([34, 54, 56, 89])

In [11]:
# Indexing and slicing
arr = np.array([10, 20, 30, 40, 50])

# Accessing single element
print("First element:", arr[0])

# Slicing the array
print("Elements from index 1 to 3:", arr[1:4])

# Multi-dimensional indexing
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Element in first row, second column:",  matrix[0, 1])

# Slicing 2D arrays
print("Second row:", matrix[1, :])

First element: 10
Elements from index 1 to 3: [20 30 40]
Element in first row, second column: 2
Second row: [4 5 6]


In [12]:
np.full((3,6),3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

**4. Basic Operations on Arrays**

**Discuss element-wise operations like addition, multiplication, and broadcasting.**

In [13]:
arr8= np.arange(32)
print(arr8)
arr9=arr8.reshape(2,2,2,2,2)
print(arr9)
arr10 = arr9.flatten()
arr10


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[[[ 0  1]
    [ 2  3]]

   [[ 4  5]
    [ 6  7]]]


  [[[ 8  9]
    [10 11]]

   [[12 13]
    [14 15]]]]



 [[[[16 17]
    [18 19]]

   [[20 21]
    [22 23]]]


  [[[24 25]
    [26 27]]

   [[28 29]
    [30 31]]]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [14]:
# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Array addition:", arr1 + arr2)

# Element-wise multiplication
print("Array multiplication:", arr1 * arr2)

# Broadcast
arr = np.array([1, 2, 3])
print("Array after scalar multiplication:", arr * 3)

Array addition: [5 7 9]
Array multiplication: [ 4 10 18]
Array after scalar multiplication: [3 6 9]


**Reshaping Arrays**

**Demonstrate reshaping of arrays and converting a 2D array to 1D.**

In [15]:
# Reshaping arrays
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print("Reshaped array (3x4):\n", reshaped_arr)

# Flattening the array
flattened_arr = reshaped_arr.flatten()
print("Flattened array:", flattened_arr)

# Using ravel()
ravel_arr = reshaped_arr.ravel()
print("Ravelled array:", ravel_arr)

Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**Random Number Generation**

**Explain how to generate random numbers with NumPy’s random module.**

In [16]:
arr11=np.random.randint(1,10,20).reshape(2,2,5)
arr11

array([[[5, 8, 1, 2, 7],
        [7, 7, 1, 1, 6]],

       [[3, 1, 1, 9, 3],
        [4, 5, 9, 8, 9]]], dtype=int32)

In [17]:

import numpy as np
# Generating random numbers
random_floats = np.random.rand(5)
print("Random floats:", random_floats)

# Random integers
random_ints = np.random.randint(1, 10, 5)
print("Random integers between 1 and 9:", random_ints)

# Set seed for reproducibility
np.random.seed(42)
random_numbers = np.random.rand(3)
print("Random numbers with seed set:", random_numbers)
var2 = np.random.randint(0,10,9).reshape(3,3)
'''array1 = np.array(var2)'''
var2
flatten = var2.flatten()
flatten

Random floats: [0.9764798  0.49268577 0.15982865 0.41595598 0.60097602]
Random integers between 1 and 9: [9 9 4 3 8]
Random numbers with seed set: [0.37454012 0.95071431 0.73199394]


array([4, 6, 9, 2, 6, 7, 4, 3, 7], dtype=int32)

**Statistical Operations**

**Discuss statistical functions like mean, median, variance, and standard deviation.**

In [18]:
# Statistical operations
arr = np.array([1, 2, 3, 4, 5])

# Mean
print("Mean:", np.mean(arr))

# Median
print("Median:", np.median(arr))

# Standard deviation
print("Standard Deviation:", np.std(arr))

# Sum
print("Sum of elements:", np.sum(arr))
var1 = np.random.randint(0,100,9).reshape(3,3)
var1

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Sum of elements: 15


array([[23,  2, 21],
       [52,  1, 87],
       [29, 37,  1]], dtype=int32)

**Working with 2D Arrays (Matrices)**

**Demonstrate matrix multiplication and transpose.**

In [19]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:\n", result)
print(matrix1)
# Transpose
print("Transpose of matrix1:\n", matrix1.T)

Matrix multiplication result:
 [[19 22]
 [43 50]]
[[1 2]
 [3 4]]
Transpose of matrix1:
 [[1 3]
 [2 4]]


**Boolean Indexing and Conditional Operations**

**Explain how to filter arrays using Boolean indexing.**

In [20]:
# Boolean indexing
arr = np.array([10, 20, 30, 40, 50])

# Filtering based on condition
print("Elements greater than 30:", arr[arr > 30])

# Using np.where
indices = np.where(arr > 30)
print("Indices where values are greater than 30:", indices)

Elements greater than 30: [40 50]
Indices where values are greater than 30: (array([3, 4]),)


In [21]:
marks=np.array([30,56,12,89,90])
print(marks[marks>33])
print(np.where(marks>33))

[56 89 90]
(array([1, 3, 4]),)
